# Generated by Django 3.0.7 on 2020-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost_found_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('pnr', models.CharField(default='', max_length=10)),
                ('building_name', models.CharField(default='', max_length=100)),
                ('class_no', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=100)),
                ('item', models.CharField(default='', max_length=10)),
                ('image', models.FileField(default='', null=True, upload_to='images/', verbose_name='')),
                ('date_time', models.DateField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='cleanliness_model',
            name='class_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cleanliness_model',
            name='pnr',
            field=models.CharField(default='', max_length=10),
        ),
    ]
