# Generated by Django 3.0.7 on 2020-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0003_auto_20201217_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanliness_model',
            name='cleaned',
            field=models.BooleanField(default=False, verbose_name='cleaned'),
        ),
        migrations.AddField(
            model_name='lost_found_model',
            name='found',
            field=models.BooleanField(default=False, verbose_name='found'),
        ),
    ]
