# Generated by Django 3.0.7 on 2020-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0004_auto_20201218_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanliness_model',
            name='cleaned',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lost_found_model',
            name='found',
            field=models.CharField(default='', max_length=100),
        ),
    ]
