# Generated by Django 3.0.7 on 2020-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0005_auto_20201218_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('prn_number', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.IntegerField(default=0)),
                ('email', models.EmailField(default=True, max_length=254, primary_key=True, serialize=False)),
                ('role', models.CharField(default='User', max_length=20)),
            ],
        ),
    ]
