# Generated by Django 3.0.7 on 2020-12-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('prn_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_dest', models.CharField(max_length=100)),
                ('max_crowd', models.IntegerField(default=0)),
                ('duration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('categeory', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('tprice', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
