# Generated by Django 3.1.3 on 2020-12-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0007_eventdetails_foods_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
