# Generated by Django 3.1.3 on 2020-12-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0008_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('date', models.CharField(default='', max_length=20)),
                ('register', models.IntegerField(default='', max_length=100)),
            ],
        ),
    ]
