# Generated by Django 3.1.3 on 2020-12-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('event_id', models.IntegerField(default=0, max_length=20)),
                ('prn', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='register',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
