# Generated by Django 3.0.7 on 2020-12-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0010_auto_20201220_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='eregister',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eregister',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
