# Generated by Django 3.0.7 on 2020-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackstar', '0011_auto_20201220_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tprice',
            field=models.CharField(default='', max_length=20),
        ),
    ]
